interpretation_settings:
  # session settings
  data_directory: "/home/nsymington/Documents/GA/dash_data_Galilee"
  # directory with the AEM data
  # The line numbers that we are interested in visualising
  lines: [ 300001, 300101, 300102, 300201, 300301, 300302, 300401, 300501,
           300502, 300503, 300504, 300601, 300602, 300603, 300604, 300701,
           300702, 300801, 300802, 300901, 301001, 301101, 301201, 301301,
           301401, 301402, 301501, 301601, 301701, 301801, 301901 ]

model_settings:
  name: "Galilee hydrostratigraphy"

  # Path to template csv file
  templateFile: "../data/surfaceTemplate.csv"
  # Path to existing interpretations
  interpFile: "../data/blank_interp_example.csv"

AEM_settings:
  name: "Galilee_AEM-data"
  # System name
  system_name: "SkyTEM_312"
  # Path to netcdf file for AEM data. If this is the file name without a path the app will search for it
  # in the data directory
  nc_path: "AUS_10024_Galilee_EM_MGA55.nc"
  # True if you want to grid the AEM data into vertical sections for visualisation false if already done.
  grid_sections: False
  # Parameters for gridding
  gridding_params: {grid_vars: [ 'low_moment_Z-component_EM_data', 'high_moment_Z-component_EM_data', 'roll',
                                 'pitch', 'tx_height_measured', 'powerline_noise', 'gps_height' ],
                    section_dir: "section_data_EM_grid"}



deterministic_inversion_settings:
  # deterministic inversion
  inversion_name: "lci"
  # Path to netcdf file for AEM deterministic inversion.
  nc_path: "Galilee_WB_MGA55.nc"
  # True if you want to grid the AEM inversion data into vertical sections for visualisation false if already done.
  grid_sections: False
  # Parameters for gridding
  gridding_params: {grid_vars: ['conductivity', 'data_residual', 'depth_of_investigation'], xres: 100., yres: 5.,
                    section_dir: "section_data_lci"}
  # path to pickle file with AEM conductivity layer grid information
  layer_grid_path: None

stochastic_inversion_settings:
  # stochastic inversion
  inversion_name: "garjmcmctdem"
  # Path to netcdf file for AEM stochastic inversion.
  nc_path: "Galilee_rjmcmc_pmaps.nc"
  grid_sections: False # True if you want to grid the AEM inversion data into vertical sections
  gridding_params: {grid_vars: [ 'conductivity_p10', 'conductivity_p50', 'conductivity_p90', 'interface_depth_histogram',
                                 'misfit_lowest', 'misfit_average' ], xres: 200., yres: 2.,
                    section_dir: "section_data_rj"}
  uncertainty: {estimate: True, # Will estimate depth uncertainty using full width half maximum method if true
                snap_interpretation: True, # will snap the interpretation to the most likely depth within this window if True
                snap_window: 20., # The size of the search window for uncertainty interpretation
                maximum_distance: 200.} # Maximum horizontal distance between pmap and interpretation for uncertainty estimation

conductivity_visualisation_settings:
  vmin: 0.01 # Starting minimum conductivity for colourstretch
  vmax: 1. # Starting maximum conductivity for colourstretch
  cmap: 'jet' # starting colourstretch
  section_plot: 'lci'
  colourbar_label: 'Conductivity (S/m)'

borehole_settings:
  include: True
  borehole_file: "Galilee_strat_proximal_to_AEM.csv"

crs:
  projected: 'EPSG:28355'
  geographic: 'EPSG:7844'
